---

#- name: Include vars of relevant parameters file for the as3 template
#  include_vars:
#    file: "{{ role_path }}/templates/as3_parameters/{{ as3_parameters_file_name }}"
 
- name: prepare the DO declaration 
  template: src="{{ role_path }}/templates/{{ do_template_file_name }}" dest="{{ role_path }}/files/{{ do_declaration_file_name }}"
  delegate_to: localhost

- name: Getting bigip authentication token
  delegate_to: localhost
  uri:
    body: '{"username":"{{ ADMIN_USER }}","password":"{{ ADMIN_PASSWORD }}","loginProvidername":"tmos"}'
    body_format: json
    method: POST
    url: "https://{{ inventory_hostname }}:{{ ADMIN_HTTPS_PORT }}/mgmt/shared/authn/login"
    status_code: 200
    validate_certs: no
  register: bigip_auth_response
  
- name: assigning auth token to a variable 
  set_fact:
    bigip_auth_token: "{{ bigip_auth_response.json.token.token }}"
    
  ##
  ## If the AS3 declaration takes time, may return a 202
  ##
- name: deploying DO declaration 
  delegate_to: localhost
  uri:
    body: "{{ lookup('file', do_declaration_file_name) }}"
    body_format: json
    headers:
      X-F5-Auth-Token: "{{ bigip_auth_token }}"
    method: POST
    status_code: 200,202
    url: "https://{{ inventory_hostname }}:{{ ADMIN_HTTPS_PORT }}/mgmt/shared/declarative-onboarding"
    validate_certs: no
    timeout: 120
  register: do_status
  until: do_status is success
  delay: 10
  retries: 20

##
## Deleting json file containing the AS3 declaration since it contains API credentials information
##

- name: delete the DO declaration file
  file: 
    path: "{{ role_path }}/files/{{ do_declaration_file_name }}"
    state: absent
  delegate_to: localhost
