---

# debugging
- name: "Ansible | Print a variable"
  debug:
    msg: "The role path is {{ role_path }}"

# Create Namespace
- name: Create a k8s namespace
  k8s:
    name: efk-logging
    api_version: v1
    host: "{{ gke1_url }}"
    kubeconfig: "{{ role_path }}/../../../kubeconfig-2"
    kind: Namespace
    state: present

# Create F5 CIS deployment with all prerequisites

# - debug:
#     var: bigip_username_encoded

# - debug:
#     var: bigip_pass_encoded

- name: Create F5 secret from a local file 
  k8s:
    state: present
    kubeconfig: "{{ role_path }}/../../../kubeconfig-2"
    definition: "{{ lookup('template', '{{ role_path }}/templates/secret_f5_cis.yml.j2') }}"

# - name: Create F5 secret with inline definition
#   k8s:
#     state: present
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: bigip-login
#         namespace: kube-system
#       type: Opaque
#       data:
#         username: "{{ bigip_username_encoded }}"
#         password: "{{ bigip_pass_encoded }}"

# - name: Create F5 secret using kubectl
#   shell:
#     cmd: kubectl create secret generic bigip-login -n kube-system --from-literal=username=admin --from-literal=password={{bigip_pass}}
#   register: create_secret
#   become: true
#   connection: ssh
# - debug: var=create_secret.stdout_lines

- name: Create ServiceAccount, Clusterrole, clusterrolebinding from a local file 
  k8s:
    state: present
    kubeconfig: "{{ role_path }}/../../../kubeconfig-2"
    src: "{{ role_path }}/templates/svcacct_crbinding_f5_cis.yml"

- name: Create the F5 Deployment from a local file and wait to become ready
  k8s:
    state: present
    kubeconfig: "{{ role_path }}/../../../kubeconfig-2"
    definition: "{{ lookup('template', '{{ role_path }}/templates/deployment_f5_cis.yml.j2') }}"
    wait: yes
    wait_condition: 
      type=Available
      status=True
    wait_timeout: 240

# Create F5 CIS configmap to expose Kibana via BIG-IP

- name: Create F5 CIS AS3 configmap from a local file 
  k8s:
    state: present
    kubeconfig: "{{ role_path }}/../../../kubeconfig-2"
    definition: "{{ lookup('template', '{{ role_path }}/templates/configmap_f5_cis.yml.j2') }}"

# - name: Get NGINX service
#   k8s_facts:
#     api_version: v1
#     kind: Service
#     name: nginx-upstream1
#     namespace: upstream1
#     kubeconfig: "{{ role_path }}/../../../kubeconfig"
#   register: nginx_svc

# - name: Get NGINX endpoints for deployment created earlier
#   k8s_facts:
#     api_version: v1
#     kind: Endpoints
#     name: nginx-upstream1
#     namespace: upstream1
#     kubeconfig: "{{ role_path }}/../../../kubeconfig"
#   register: nginx_ep

# - name: debug 
#   debug: var=nginx_ep

# - name: Generate list of NGINX endpoints from the registered variable nginx_ep
#   # Currently this assumes 1 IP address in the list 
#   set_fact: 
#     ep_list: "{{ [nginx_ep.resources[0].subsets[0].addresses[0].ip, nginx_ep.resources[0].subsets[0].ports[0].port]|join(':') }}"

# - name: debug 
#   debug: var=ep_list