---
# Ensure SSH connectivity
- name: Wait a maximum of 120 seconds for BIG-IP port 22
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    timeout: 180
  delegate_to: localhost

# Get BIG-IP facts
- name: Collect BIG-IP Facts
  bigip_device_info:
    gather_subset:
      - devices
    provider:
      server: "{{ inventory_hostname }}"
      user: "{{ ADMIN_USER }}"
      password: "{{ ADMIN_PASSWORD }}"
      server_port: 8443
      validate_certs: no
  delegate_to: localhost
  register: device_facts

# Debug
- name: Display complete information about BIG-IP Device
  debug:
    var: device_facts

# Debug
- name: Display only hostname of BIG-IP Device
  debug:
    var: device_facts['devices']['hostname']

- name: Set new bigip_hostname from device_facts
  # Currently this assumes 1 IP address in the list 
  set_fact: 
    bigip_hostname: "{{ device_facts['devices']['hostname'] }}"

- name: Provision ASM at "nominal" level
  bigip_provision:
    module: asm
    level: nominal
    provider:
      server: "{{ inventory_hostname }}"
      server_port: "{{ ADMIN_HTTPS_PORT }}"
      user: "{{ ADMIN_USER }}"
      password: "{{ ADMIN_PASSWORD }}"
    validate_certs: no
  delegate_to: localhost
  register: provision_status
  until: provision_status is success
  delay: 10
  retries: 20

# Create partition used for CIS
- name: Create partition "k8s" using the default route domain
  bigip_partition:
    name: k8s
    provider:
      server: "{{ inventory_hostname }}"
      server_port: "{{ ADMIN_HTTPS_PORT }}"
      user: "{{ ADMIN_USER }}"
      password: "{{ ADMIN_PASSWORD }}"
    validate_certs: no
  delegate_to: localhost